theme: jekyll-theme-minimal
title: Coding and Data Analysis Portfolio
logo: https://bioboot.github.io/bimm143_W23/assets/img/logo.png
description: My projects from Bioinformatics and Neurobiology Labs
